server:
    port: 8088
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3000/design_ms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
#        服务器配置
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 50MB
    thymeleaf:
        prefix: classpath:/static/
        suffix: .html
        cache: false #关闭缓存
    profiles:
        active: dev
    mail:
        # 配置 SMTP 服务器地址
        host: smtp.qq.com
        # 发送者邮箱
        username: 1170959543@qq.com
        # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
        password: tvkfyleechbgfgeg
        # 端口号465或587
        port: 587
        # 默认的邮件编码为UTF-8
        default-encoding: UTF-8
        # 配置SSL 加密工厂
        properties:
            mail:
                smtp:
                    socketFactoryClass: javax.net.ssl.SSLSocketFactory
                #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
                debug: true
